### ISSUE TITLE
Wrong behavoir proccecing really fast events ¿?

### ISSUE THREAD

**Issue by Scheriderm** [Mokosha/netwire-input-glfw#1]
If more than one event happend before the event wire is step only the last event will be registered (and only if this prolong enough time to be catch it ) . The unprocessed event will be erase from the monad before the event wire use them.  
http://lpaste.net/120485
 I don't know if this is an issue or just something that i should avoid to do...

**Comment by Mokosha** [comment]
Do you mean to say that if you press and release a key between `GLFW.pollEvents` calls that the keypress doesn't register?

**Comment by Scheriderm** [comment]
No. That if you press and release a key and then make a poll, two events will be trigger. One will put the key in the glfw monad and the other will erase it from it. And then when you want it to step your logic the glfw monad will look like there wasn't any change at all.
 Sorry for my bad english

**Comment by MaxDaten** [comment]
@Scheriderm and I discussed it via IRC, I had the same issue with my own implementation. Kudos to yours, my implementation was really clumsy.

But the problem is the `Set` in the backend. Events have a order. You can't implement a typewriter with a Set because you will lose the order of the keystrokes or especially the keystroke itself when the *push down" and "release" was in the same timeframe. A user of your framework can solve it with pushing events one after another in the wire system (with `dt=0`, my current solution in my implementation). But your `pollGLFW` is a pitfall because it will drop every self eliminating event.

**Comment by Mokosha** [comment]
OK, I'm not sure what the correct fix is here. The solution you're suggesting breaks some semantics about how wires behave w.r.t. FRP: a wire shouldn't be able to produce two separate values at the same instance of time `t`. Obviously there are game scenarios when registering the events between a timestep are relevant (e.g. fighting games). I find this to be a limitation of FRP in some respects, although there is a fix I'm OK with:
- Along with the `Set` of pressed/released keys, buffer events and flush it just after `pollGLFW` call.
- Provide another function (and wire) in `MonadInput` from `netwire-input` to retrieve list of buffered events that users can query for up/down button (key, mouse, & joystick) presses.

The second bullet point is a little bit yucky because what goes into that buffered list is going to be implementation dependent. What this means is that if you switch out your input backend from `netwire-input-glfw` to (e.g.) `netwire-input-sdl2` you'd have to figure out what logic code suddenly broke because the buffered values might be different. As it stands right now, swapping out backends shouldn't affect game logic as long as the backend properly fulfills the `MonadInput` contract.
